config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "static_pages/home"
    get "static_pages/about"
    get "static_pages/contact"
    get "/search", to: "products#search"
    devise_for :users
    as :user do
      get "/login", to: "devise/sessions#new"
      post "/login", to: "devise/sessions#create"
      delete "/logout", to: "devise/sessions#destroy"
    end
    resources :cart_sessions, only: %i(index create) do
      collection do
        post "change"
        delete "remove"
      end
    end
    
    resources :cart_sessions
    resources :static_pages

    namespace :admin do
      root "admins#index"
      resources :users, only: :index
      resources :orders, only: %i(index update)
      resources :products, only: :index
    end

    resources :users, except: %i(index destroy)
    resources :categories do
      resources :products, only: :show
    end
  end
end

app/views/admin/admins/_left_bar.html.erb
<nav class="navbar-default navbar-side" role="navigation">
  <div class="sidebar-collapse">
    <ul class="nav" id="main-menu">
      <li>
        <%= link_to admin_root_path do %>
          <i class="fa fa-dashboard fa-3x"></i>
          <span><%= t("static_pages.home.home") %></span>
        <% end %>
      </li>
      <li>
        <%= link_to admin_users_path, remote: true do %>
          <i class="fa fa-user fa-3x"></i>
          <span><%= t("user.manage.user") %></span>
        <% end %>
      </li>
      <li>
        <%= link_to "#" do %>
          <i class="fa fa-list fa-3x"></i>
          <span><%= t("categories.title") %></span>
        <% end %>
      </li>
      <li>
        <%= link_to admin_products_path, remote: true do %>
        <i class="fa fa-cutlery fa-3x"></i>
          <span><%= t("product") %></span>
        <% end %>
      </li>
      <li>
        <%= link_to admin_orders_path, remote: true do %>
          <i class="fa fa-pencil-square-o fa-3x"></i>
          <span><%= t("orders.title") %></span>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/admin/admins/index.html.erb
<%= render "left_bar" %>
<div id="page-wrapper">
  <div id="notice">
    <% unless notice.blank?
         render partial: "shared/notice_banner"
       end %>
</div>
  <div id="page-inner">
    <div class="row">
        <div class="col-md-12">
            <h2><%= t("admin.manage.title") %></h2>
        </div>
    </div>
    <hr />
  </div>
</div>