config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "static_pages/home"
    get "static_pages/about"
    get "static_pages/contact"
    get "/search", to: "products#search"
    devise_for :users
    as :user do
      get "/login", to: "devise/sessions#new"
      post "/login", to: "devise/sessions#create"
      delete "/logout", to: "devise/sessions#destroy"
    end
    resources :cart_sessions, only: %i(index create) do
      collection do
        post "change"
        delete "remove"
      end
    end
    
    resources :cart_sessions
    resources :static_pages

    namespace :admin do
      root "admins#index"
      resources :users, only: :index
      resources :orders, only: %i(index update)
      resources :products, only: :index
    end

    resources :users, except: %i(index destroy)
    resources :categories do
      resources :products, only: :show
    end
  end
end

app/models/cart_session.rb
class CartSession < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :quantity, presence: true, numericality: {only_integer: false}
end

app/controllers/cart_sessions_controller.rb
class CartSessionsController < ApplicationController
  before_action :check_quantity, only: %i(create change remove)
  before_action :check_exist_product_id, only: %i(remove change)

  def index; end

  def change
    current_cart[params[:product_id].to_s] = params[:quantity].to_f
    flash.now[:success] = t "carts.update.success"
    @product_id = params[:product_id]
  end

  def remove
    current_cart.delete params[:product_id]
    flash.now[:success] = t "carts.delete.delete_success"
    @product_id = params[:product_id]
  end

  def create
    sp_create
    flash.now[:success] = t "carts.create.success"
  end

  private

  def cart_session_params
    params.require(:order_product).permit(:product_id, :quantity)
  end

  def check_quantity
    if @product = Product.find_by(id: params[:product_id])
      sp_check_quantity
    else
      flash[:danger] = t "carts.create.not_success"
      redirect_to cart_sessions_path
    end
  end

  def sp_create
    if !current_cart[params[:product_id].to_s]
      current_cart[params[:product_id].to_s] = @quantity
    else
      current_cart[params[:product_id].to_s] += @quantity
    end
  end

  def sp_check_quantity
    @quantity = params[:quantity].to_f
    return unless @quantity > @product.quantity.to_f || check_sum

    flash[:danger] = t "carts.create.not_success"
    redirect_to cart_sessions_path
  end

  def check_sum
    sum = current_cart[params[:product_id].to_s].to_f + @quantity
    @product.quantity < sum
  end

  def check_exist_product_id
    return if session[:cart][params[:product_id]]

    flash[:warning] = t "cart.update.not_exist_products"
    redirect_to cart_sessions_path
  end
end

app/views/cart_sessions/_cart_row.html.erb
<td><%= product.name %></td>
<td><%= number_to_currency(product.price, locale: :vi) %></td>
<td><%= product_image product %></td>
<td>
  <%= form_tag change_cart_sessions_path,remote:true do %>
    <%= number_field_tag :quantity, nil, step: 0.1, value: current_cart[product.id.to_s].round(1), required: true, min: 0.1, max: product.quantity %>
    <%= hidden_field_tag :product_id, nil, value: product.id %>
    <%= button_tag t("carts.update.update_cart"), class: "button" %>
  <% end %>
</td>
<td><%= number_to_currency(into_money(product), locale: :vi) %></td>
<td>
  <%= link_to t("carts.update.delete_cart"), remove_cart_sessions_path(product_id: product.id), {data: {confirm: t("carts.delete.alert_delete")}, method: :delete, remote: true, class: "btn-close"} %>
</td>

app/views/cart_sessions/change.js.erb
$('#flash_messase').html('<%= j render "layouts/flash" %>')
$('#cart_area').html('<%= j render "layouts/cart_area" %>')
$('#row-<%= @product_id %>').html('<%= j render "cart_sessions/cart_row", product: @product %>')
$('#total').html('<%= into_money_cart %>')

app/views/cart_sessions/create.js.erb
$('#flash_messase').html('<%= j render "layouts/flash" %>')
$('#cart_area').html('<%= j render "layouts/cart_area" %>')

app/views/cart_sessions/index.html.erb
<h1><%= t "products.show.cart" %></h1>
<div class="shopping_cart_area">
  <div class="row">
    <div class="col-12">
      <div class="table_desc">
        <div class="cart_page table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th scope="col"><%= t "products.show.name" %></th>
                <th scope="col"><%= t "products.show.price" %></th>
                <th scope="col"><%= t "products.show.image" %></th>
                <th scope="col"><%= t "products.show.quantity" %></th>
                <th scope="col"><%= t "products.show.total_price" %></th>
                <th scope="col"><%= t "products.show.action" %></th>
              </tr>
            </thead>
            <tbody>
              <% load_products.each do |product| %>
                <tr id="row-<%= product.id %>">
                  <%= render "cart_sessions/cart_row", product: product %>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="coupon_area">
  <div class="row">
    <div class="col-lg-6 col-md-6">
      <div class="coupon_code right">
        <h3><%= t "products.show.cart_totals" %></h3>
          <div class="coupon_inner">
            <div class="cart_subtotal">
              <p><%= t "products.show.subtotal" %></p>
              <p id="total" class="cart_amount"><%= into_money_cart %></p>
            </div>
            <div class="checkout_btn">
              <%= link_to t("carts.update.checkout"), orders_path, method: :post %>
            </div>
          </div>
      </div>
     </div>
  </div>
</div>

app/views/cart_sessions/remove.js.erb
$('#flash_messase').html('<%= j render "layouts/flash" %>')
$('#cart_area').html('<%= j render "layouts/cart_area" %>')
$('#row-<%= @product_id %>').html('')
$('#total').html('<%= into_money_cart %>')