config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "static_pages/home"
    get "static_pages/about"
    get "static_pages/contact"
    get "/search", to: "products#search"
    devise_for :users
    as :user do
      get "/login", to: "devise/sessions#new"
      post "/login", to: "devise/sessions#create"
      delete "/logout", to: "devise/sessions#destroy"
    end
    resources :cart_sessions, only: %i(index create) do
      collection do
        post "change"
        delete "remove"
      end
    end
    
    resources :cart_sessions
    resources :static_pages

    namespace :admin do
      root "admins#index"
      resources :users, only: :index
      resources :orders, only: %i(index update)
      resources :products, only: :index
    end

    resources :users, except: %i(index destroy)
    resources :categories do
      resources :products, only: :show
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_prodcuts, dependent: :nullify
  has_many :cart_details, dependent: :destroy
  has_one_attached :image

  validates :name, presence: true
  validates :price, presence: true, numericality: {only_integer: false}
  validates :quantity, presence: true, numericality: {only_integer: false}
  validates :description, presence: true,
    length: {minimum: Settings.product.min_description}
  validates :image,
            content_type: {
              in: Settings.product.image_type,
              message: :image_invalid_type
            },
            size: {
              less_than: Settings.product.image_size.megabytes,
              message: :image_invalid_size
            }
  scope :search_categories, (lambda do |key|
    joins(:category)
    .where("categories.name LIKE ?", "%#{key}%")
  end)
  scope :search_products, ->(key){where "products.name LIKE ?", "%#{key}%"}
  scope :load_by_ids, ->(ids){where id: ids}

  def handle_update_quantity quantity_order
    update_attribute :quantity, quantity - quantity_order
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminsController
  def index
    @products = Product.page(params[:page])
                       .per(Settings.per_page.per_5)
    respond_to do |format|
      format.html{redirect_to admin_root_path}
      format.js
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @product = Product.find_by id: params[:id]
    store_location
    return if @product

    flash[:danger] = t "product.not_found"
    redirect_to root_path
  end

  def search
    @products = Product.search_categories(params[:search])
                       .or(Product.search_products(params[:search]))
                       .distinct.page(params[:page])
                       .per(Settings.length.pages_10)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def product_image product
    if product.image.attached?
      image_tag product.image, class: "image_size"
    else
      image_tag "product/default_image.jpg", class: "image_size"\
    end
  end
end

app/views/products/_product.html.erb
<div class="col-md-4 col-sm-6 col-lg-3">
  <div class="single_product">
    <div class="product_thumb">
      <%= image_tag product.image %>
      <div class="quick_button">
        <%= link_to t("products.show.detail_product"), [product.category, product] %>
      </div>
      <div class="double_base">
        <div class="product_sale">
          <span></span>
        </div>
        <div class="label_product">
          <span></span>
        </div>
      </div>
    </div>
    <div class="product_content grid_content">
      <h3><%= product.name %></h3>
      <span class="current_price"><%= number_to_currency product.price %></span>
    </div>
  </div>
</div>

app/views/products/search.html.erb
<% provide :title, t("categories.show.product_category_id") %>
<% if @products.any? %>
  <div class="row shop_wrapper grid_4">
    <%= render @products %>
  </div>
  <div class="shop_toolbar t_bottom">
    <div class="pagination">
      <%= paginate @products %>
    </div>
  </div>
<% else %>
  <h2><%= t("products.search.not_found") %></h2>
<% end %>

app/views/products/show.html.erb
<% provide :title, t("products.show.detail_product") %>
<div class="breadcrumbs_area product_bread">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="breadcrumb_content">
          <ul>
            <li><%= link_to t("static_pages.home.home") %></li>
            <li>/</li>
            <li><%= t("products.show.detail_product") %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="product_details">
  <div class="container">
    <div class="row">
      <div class="col-lg-5 col-md-5">
        <div class="product-details-tab">
          <div id="img-1" class="zoomWrapper single-zoom">
            <%= product_image @product%>
          </div>
        </div>
      </div>
      <div class="col-lg-7 col-md-7">
        <div class="product_d_right">
          <h1><%= @product.name %></h1>
          <div class="product_price">
            <span class="current_price">
              <%= number_to_currency @product.price %>
            </span>
          </div>
          <div class="product_desc">
            <p><%= @product.description %></p>
          </div>
          <div class="product_variant quantity">
          <% if @product.quantity != 0 %>
            <%= form_tag cart_sessions_path, remote: true do |f| %>
              <label><%= t("products.show.quantity") %></label>
              <%= number_field_tag :quantity, nil, step: 0.1, value: 0.1, required: true, min: 0.1, max:@product.quantity %>
              <%= hidden_field_tag :product_id, nil, value: @product.id %>
              <% if user_signed_in? %>
                <%= button_tag t("products.show.add_to_cart"), class:  "button" %>
              <% else %>
                <%= link_to t("products.show.request_login"), login_path, class: "button" %>
              <% end %>
            <% end %>
          <% else %>
            <%= button_tag t("products.show.out_of_products"), class: "button" %>
          <% end %>
          </div>
          <div class="priduct_social">
            <h3><%= t("products.show.share_on") %></h3>
            <ul>
              <li>
                <i class="fa fa-rss"></i>
              </li>
              <li>
                <i class="fa fa-vimeo"></i>
              </li>
              <li>
                <i class="fa fa-tumblr"></i>
              </li>
              <li>
                <i class="fa fa-pinterest"></i>
              </li>
              <li>
                <i class="fa fa-linkedin"></i>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>